services:
  workspace:
    build:
      context: .docker/workspace
      args:
        NODEJS_VERSION: ${NODEJS_VERSION:-20}
      target: development
    user: root
    env_file:
      - .env.dist
      - .env.local
    environment:
      - GITHUB_TOKEN
      - NPM_TOKEN
    volumes:
      - .:/opt/${COMPOSE_PROJECT_NAME}:cached
    working_dir: /opt/${COMPOSE_PROJECT_NAME}
