services:
  workspace:
    build:
      context: .docker/workspace
      args:
        NODEJS_VERSION: ${NODEJS_VERSION:-20}
      target: development
    user: root
    env_file:
      - .env.dist
      - .env.local
    environment:
      - GITHUB_TOKEN
      - NPM_TOKEN
    # links:
    #   - nginx
    #   - redis
    volumes:
      - .:/opt/${COMPOSE_PROJECT_NAME}:cached
    working_dir: /opt/${COMPOSE_PROJECT_NAME}

  nginx:
    image: nginx:1-alpine
    expose:
      - 8080
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached,ro

  redis:
    image: redis:7-alpine
    expose:
      - 6379
