services:
  nodejs:
    build:
      context: .docker/nodejs
      args:
        NODEJS_VERSION: ${NODEJS_VERSION:-18}
      target: development
    user: root
    env_file:
      - .env.dist
      - .env.local
    environment:
      - GITHUB_TOKEN
      - NPM_TOKEN
    links:
      - nginx
      - redis
    volumes:
      - .:/dist/${COMPOSE_PROJECT_NAME}:cached
    working_dir: /dist/${COMPOSE_PROJECT_NAME}

  nginx:
    image: nginx:1-alpine
    expose:
      - 8080
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached,ro

  redis:
    image: redis:7-alpine
    expose:
      - 6379
