services:
  nodejs:
    build:
      context: .docker/nodejs
      args:
        NODEJS_VERSION: ${NODEJS_VERSION:-18}
      target: development
    user: root
    env_file:
      - .env.dist
      - .env.local
    environment:
      - GITHUB_TOKEN
      - NPM_TOKEN
    links:
      - redis7
    volumes:
      - .:/dist/${COMPOSE_PROJECT_NAME}:cached
    working_dir: /dist/${COMPOSE_PROJECT_NAME}

  redis7:
    image: redis:7-alpine
    expose:
      - 6379
