x-nodejs18: &nodejs18
  build:
    context: .docker/nodejs
    args:
      NODEJS_VERSION: 18
    target: base
  user: node

services:
  nodejs18:
    <<: *nodejs18
    env_file:
      - .env.dist
      - .env.local
    links:
      - redis7
    volumes:
      - .:/compose:cached
    working_dir: /compose
    command: ['npm', 'install', '--from-lockfile']

  redis7:
    image: redis:7-alpine
    expose:
      - 6379
