name: test
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NODEJS_VERSION: [16, 18, 20, 21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
          cache: npm
      - run: make _build
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NODEJS_VERSION: [16, 18, 20, 21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODEJS_VERSION }}
          cache: npm
      - run: make _test
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
